### ISSUE TITLE
Inconsistency in Team.forward()

### ISSUE THREAD

**Issue by semiwaker** [batra-mlp-lab/lang-emerge#7]
Hello, I tried to reproduce your result, and find something that seams like a bug.
In chatbots.py, line 265, `self.guessToken, self.guessDistr = self.qBot.predict(tasks, 2)`
Back to line 236, the task is added by taskOffset `aBotReply = tasks + self.qBot.taskOffset` and passed to `self.qBot.listen`. Since the embedding layer `self.inNet` is the same in the two methods `listen` and `predict`, there seams to be some inconsistency because the offset is not added in line 236.
I wonder if it is my misunderstanding or it is really a bug. Thanks.

**Comment by satwikkottur** [comment]
Hello @semiwaker ,
Thanks for identifying this bug. Realized that I never used the `embedTask` method that was probably written for this purpose. Let me know if the commit fixes it.

This should make learning slightly easier since first few embeddings in `inNet` are not overloaded to capture multiple semantics.

**Comment by semiwaker** [comment]
After fixing the bug, training speeds up a little bit. I think the commit works. Thanks.
